// UCRPGAttributeSet.cpp
// PROJECT: A Nameless World
// PURPOSE: Implements the functions declared in UCRPGAttributeSet.h
//          This file contains the actual logic — the "how it works" half.
//
// RULE: This file is compiled ONCE. That is why function bodies live here
//       and not in the .h file (which gets included by many files).

#include "Attributes/UCRPGAttributeSet.h"
// Include our own header first — always.
// Path is relative to the Public/ folder, which UBT adds to the include paths.

#include "GameplayEffectExtension.h"
// Provides FGameplayEffectModCallbackData — the struct passed to
// PostGameplayEffectExecute that tells us which attribute changed and by how much.

#include "GameFramework/Character.h"
// Provides ACharacter — we cast the owning actor to this to call Die().


// ── Constructor ──────────────────────────────────────────────────────────────

UCRPGAttributeSet::UCRPGAttributeSet()
// This runs once when a character spawns and its AbilitySystemComponent
// registers this AttributeSet. Sets all starting values.
{
    // ── Vitals ──
    // InitX() sets the BaseValue. GAS will copy it to CurrentValue on init.
    InitHealth(100.f);      // All characters start with 100 HP
    InitMaxHealth(100.f);   // Ceiling for Health — used in clamping below
    InitMana(50.f);         // Protagonist uses Mana for word abilities
    InitMaxMana(50.f);

    // ── D&D Core Stats (default human — 10 in everything = modifier 0) ──
    // These will be overridden per-character via DataAssets in a later session.
    // 10 is the D&D "average human" baseline: modifier = floor((10-10)/2) = 0
    InitStrength(10.f);
    InitDexterity(10.f);
    InitIntelligence(10.f);
    InitWisdom(10.f);
    InitCharisma(10.f);
    InitConstitution(10.f);

    // ── Progression ──
    InitXP(0.f);        // Everyone starts with 0 XP
    InitCharacterLevel(1.f);     // Everyone starts at Level 1
    // NOTE: Level stored as float because FGameplayAttributeData requires float.
    //       When reading Level for logic, cast to int32: (int32)GetLevel()
}


// ── PostGameplayEffectExecute ────────────────────────────────────────────────

void UCRPGAttributeSet::PostGameplayEffectExecute(
    const FGameplayEffectModCallbackData& Data)
// GAS calls this automatically after EVERY GameplayEffect modifies an attribute.
// "Data" contains: which attribute changed, by how much, who caused it, who received it.
{
    // Call the parent version first — UE5 best practice.
    // The base UAttributeSet::PostGameplayEffectExecute does internal bookkeeping
    // that we must not skip.
    Super::PostGameplayEffectExecute(Data);

    // ── Who owns this AttributeSet? ──────────────────────────────────────────
    // The AttributeSet lives on a character. We need a pointer to that character
    // so we can call Die() on it when Health reaches 0.
    ACharacter* OwningCharacter = Cast<ACharacter>(GetOwningActor());
    // Cast<> is UE5's safe type conversion.
    // If GetOwningActor() is not an ACharacter (e.g. a turret), Cast returns nullptr.
    // We check for nullptr before using the pointer (see below).


    // ── CLAMP AND REACT: Health ───────────────────────────────────────────────
    // Check if the attribute that just changed was Health.
    // Data.EvaluatedData.Attribute is the FGameplayAttribute handle for what changed.
    if (Data.EvaluatedData.Attribute == GetHealthAttribute())
    // GetHealthAttribute() was generated by ATTRIBUTE_ACCESSORS in the .h file.
    // It returns the unique identifier for the Health attribute.
    {
        // Clamp Health between 0 and MaxHealth.
        // FMath::Clamp(value, min, max) — UE5's built-in clamp utility.
        // WHY CLAMP? Without this, a 200-damage hit on a 100HP enemy could result
        // in Health = -100. Negative health causes undefined behaviour in UI and logic.
        float ClampedHealth = FMath::Clamp(GetHealth(), 0.f, GetMaxHealth());
        SetHealth(ClampedHealth);
        // SetHealth() was also generated by ATTRIBUTE_ACCESSORS.

        // ── Death trigger ────────────────────────────────────────────────────
        if (GetHealth() <= 0.f && OwningCharacter != nullptr)
        // Two conditions:
        //   GetHealth() <= 0.f  — health actually hit zero
        //   OwningCharacter != nullptr — we have a valid pointer to call Die() on
        //
        // WHY CHECK nullptr? If we skip this and OwningCharacter is nullptr,
        // calling OwningCharacter->Die() dereferences a null pointer → crash.
        {
            // TODO (Session 2): Call OwningCharacter->Die() once ABaseCharacter exists.
            // For now we log to the Output Log so we can verify the trigger works.
            UE_LOG(LogTemp, Warning,
                TEXT("PostGameplayEffectExecute: %s Health reached 0 — Die() will be called here."),
                *OwningCharacter->GetName());
            // UE_LOG format:
            //   LogTemp   — which log category (LogTemp is the generic scratch category)
            //   Warning   — severity (Log, Warning, Error)
            //   TEXT("…") — the message string (TEXT() macro handles wide chars)
            //   *GetName()— dereferences FString to raw TCHAR* that %s expects
        }
    }


    // ── CLAMP: Mana ──────────────────────────────────────────────────────────
    if (Data.EvaluatedData.Attribute == GetManaAttribute())
    {
        float ClampedMana = FMath::Clamp(GetMana(), 0.f, GetMaxMana());
        SetMana(ClampedMana);
        // No death trigger for Mana — running out of Mana just prevents ability use.
    }


    // ── CLAMP: Core Stats (prevent absurd values from stacking buffs) ────────
    // Stats should stay in a sane range. 1–30 covers all D&D 5e use cases.
    // A stat of 0 would produce modifier floor((0-10)/2) = -5, which is valid
    // but we disallow 0 to avoid divide-by-zero elsewhere.
    const float STAT_MIN = 1.f;
    const float STAT_MAX = 30.f;

    // Clamp each D&D core stat after any effect modifies it.
    // GAS has no generic SetAttributeValue — each attribute has its own
    // typed setter generated by ATTRIBUTE_ACCESSORS.
    if (Data.EvaluatedData.Attribute == GetStrengthAttribute())
        SetStrength(FMath::Clamp(GetStrength(), STAT_MIN, STAT_MAX));
    else if (Data.EvaluatedData.Attribute == GetDexterityAttribute())
        SetDexterity(FMath::Clamp(GetDexterity(), STAT_MIN, STAT_MAX));
    else if (Data.EvaluatedData.Attribute == GetIntelligenceAttribute())
        SetIntelligence(FMath::Clamp(GetIntelligence(), STAT_MIN, STAT_MAX));
    else if (Data.EvaluatedData.Attribute == GetWisdomAttribute())
        SetWisdom(FMath::Clamp(GetWisdom(), STAT_MIN, STAT_MAX));
    else if (Data.EvaluatedData.Attribute == GetCharismaAttribute())
        SetCharisma(FMath::Clamp(GetCharisma(), STAT_MIN, STAT_MAX));
    else if (Data.EvaluatedData.Attribute == GetConstitutionAttribute())
        SetConstitution(FMath::Clamp(GetConstitution(), STAT_MIN, STAT_MAX));


    // ── CLAMP: Level (1 minimum, no maximum enforced here) ───────────────────
    if (Data.EvaluatedData.Attribute == GetCharacterLevelAttribute())
    {
        float ClampedLevel = FMath::Max(GetCharacterLevel(), 1.f);
        // FMath::Max(a, b) returns the larger of a and b.
        // This ensures Level can never fall below 1 (de-level effects in V2+).
        SetCharacterLevel(ClampedLevel);
    }
}


// ── GetModifier ───────────────────────────────────────────────────────────────

int32 UCRPGAttributeSet::GetModifier(float StatScore) const
// Calculates the D&D 5e ability modifier from a raw stat score.
// Called by: combat roll system, Initiative, ability DC calculation.
//
// Formula: floor((Score - 10) / 2)
// Why floor? Negative halves round DOWN in D&D (score 9 → (9-10)/2 = -0.5 → -1)
// FMath::FloorToInt handles this correctly for both positive and negative values.
{
    // Step 1: Subtract the baseline (10 = "average human" = modifier 0)
    float Diff = StatScore - 10.f;

    // Step 2: Halve it and floor to nearest integer
    int32 Modifier = FMath::FloorToInt(Diff / 2.f);

    // Quick reference for the common scores you will see in the game:
    // Score  8 → Modifier -1   (below average)
    // Score 10 → Modifier  0   (human baseline)
    // Score 12 → Modifier +1
    // Score 14 → Modifier +2
    // Score 16 → Modifier +3   (protagonist's INT target)
    // Score 18 → Modifier +4   (exceptional)
    // Score 20 → Modifier +5   (near-superhuman)

    return Modifier;
}
